### PR TITLE
Allow grouping to work

### PR DESCRIPTION
**Pull request by amritk**
Not sure if this is worth merging here, or maybe we pass the regex in as an option. This allows tailwind grouping to work for vite users.

https://github.com/tailwindlabs/tailwindcss/discussions/11701

https://github.com/rschristian/tailwind-grouping

### CODE REVIEW

**Comment by amritk** [comment]
Ah looks like I will need to adjust the sorting bit as well

**Comment by thecrypticace** [comment]
Hey, so properly supporting this would require a lot more work, figuring out exactly how we'd want grouping to work, and how sorting works within a group. This is because all sorting is actually handled by Tailwind CSS (since v3.2 iirc — it's been a minute). This means the actual sorting logic would require grouping to be built into Tailwind CSS itself. The Prettier plugin is basically a glorified parsing mechanism that pulls out lists of classes in a "smart" manner, sorts them, and writes them back to the soure code.

We did some tests a [long while ago](https://twitter.com/adamwathan/status/1461519824828473359) that showed that variant grouping results in larger file sizes in basically any realistic scenario — including after compression. So, while the class lists may look shorter in your HTML the end result is your CSS file grows pretty significantly because the generated classes are much less reusable. This is why supporting grouping is pretty much non-goal for us right now. We shipped an experimental version of variant grouping in May-ish of 2022 and then disabled it not long after. I finally ripped out the code myself a few months ago.

Appreciate the PR but gonna close this as it's not something we're wanting to support.

**Comment by amritk** [comment]
Ah yea I read through the discussions, but in this case grouping does not result in any extra css as the grouping gets transformed into regular classes before tailwind see's it. That's why I was so excited when I found this plugin!

That is unfortunate that the sorting comes from tailwind! I was hoping it would be in this plugin and I could just make a tweak. Fair enough maybe I will do some sort of hacky fork that gets it working, just for us Vite/Babel/wmr users that can use grouping with no consequences.

Thanks for taking a look!

**Comment by rschristian** [comment]
> We did some tests a [long while ago](https://twitter.com/adamwathan/status/1461519824828473359) that showed that variant grouping results in larger file sizes in basically any realistic scenario

This is only the case if you don't expand them, FWIW. If you do (as the linked Babel plugin does) there's 0 difference in size.

I appreciate that sort of transform is going to be outside the current scope of Tailwind, however.

**Pull request closed without merging**
